# Generated by Django 6.0.5 on 2026-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_open_match',
            field=models.BooleanField(default=False),
        ),
    ]
