# Generated by Django 6.0.5 on 2026-06-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('pickleball', 'Pickleball')], default='pickleball'),
            preserve_default=False,
        ),
    ]
