# Generated by Django 6.0.5 on 2026-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_court_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterUniqueTogether(
            name='courtschedule',
            unique_together={('court', 'day_of_week')},
        ),
    ]
